spring:
  datasource:    url: jdbc:mysql://localhost:3306/dbspotmusic?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update